#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input medium osm-data-mapnik/initdb || true
db_input medium osm-data-mapnik/grant_user || true
db_go || true

db_get osm-data-mapnik/initdb || true
INIT_DB=$RET
db_get osm-data-mapnik/grant_user || true
GRANT_USER=$RET

cat <<EOF > /etc/default/osm-data-mapnik
# Default settings for osm-data-mapnik
GRANT_USER="$GRANT_USER"
INIT_DB="$INIT_DB"
EOF

